# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Han Loong Liauw
tagline:          'because the world needs another programming blog'
description:      "thoughts and experiences on programming and related topics. <p>Ruby, Rails, PHP, coffeescrpt, javascript, scala</p>"
url:              http://hanloong.me

author:
  name:           'Han Loong Liauw'
  url:            https://twitter.com/hanliauw

paginate:         5
paginate_path:    "/blog/page:num/"

# Custom vars
version:          1.0.0

github:
  name:           'Github'
  repo:           https://github.com/hanloong/hanloong.github.com
  profile:        https://github.com/hanloong

twitter:
  name:           'Twitter'
  link:           https://twitter.com/hanliauw

instagram:
  name:           'Instagram'
  link:           https://instagram.com/hanloong

stackoverflow:
  name:           'Stack Overflow'
  link:           http://stackoverflow.com/users/2663005/han-loong-liauw

blog:
  name:           'Blog Posts'
  link:           http://hanloong.me/blog

resume:
  name:           'Résumé'
  link:           http://hanloong.me/resume/

sass:
  sass_dir:       _sass
  style:          :compressed
