# Gems
gems: [jekyll-paginate]

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Han Loong Liauw
tagline:          Mostly abandoned and incomplete thoughts
description:      Thoughts and experiences on programming and related topics
url:              http://hanloong.me

author:
  name:           'Han Loong Liauw'
  url:            https://twitter.com/hanliauw

paginate:         5
paginate_path:    "/blog/page:num/"

# Custom vars
version:          1.0.0

github:
  name:           '@hanloong'
  repo:           https://github.com/hanloong/hanloong.github.com
  profile:        https://github.com/hanloong

twitter:
  name:           '@hanliauw'
  link:           https://twitter.com/hanliauw

instagram:
  name:           'Instagram'
  link:           https://instagram.com/hanloong

stackoverflow:
  name:           'Stack Overflow'
  link:           http://stackoverflow.com/users/2663005/han-loong-liauw

blog:
  name:           'Blog'
  link:           http://hanloong.me/blog

resume:
  name:           'Résumé'
  link:           http://hanloong.me/resume/

exercism:
  name:           "exercism.io"
  link:           http://exercism.io/profiles/hanloong/f44221b854e54ac29d6d16ec74665a57

sass:
  sass_dir:       _sass
  style:          :compressed
